version: '3.8'


services:
    chrome:
        image: selenium/standalone-chrome:latest
        hostname: chrome
        privileged: true
        shm_size: 2g
        healthcheck:
          test: ["CMD", "curl", "-f", "http://chrome:4444"]
          interval: 5s
          timeout: 5s
          retries: 10
    app:
        build: .
        stdin_open: true # docker run -i
        tty: true 
        depends_on: 
          chrome:
            condition: service_healthy

